modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "archers_paradox"
version = "${file.jarVersion}"
displayName = "Archer's Paradox"
updateJSONURL = "https://raw.github.com/cofh/version/master/archers_paradox/update.json"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Adds many new varieties of arrows.

Suitable for both lightly and heavily modded worlds.
'''
[[dependencies.archers_paradox]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.archers_paradox]]
modId = "forge"
mandatory = true
versionRange = "[36.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.archers_paradox]]
modId = "cofh_core"
mandatory = true
versionRange = "[1.3,1.4]"
ordering = "AFTER"
side = "BOTH"